name: deploy-now
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Test
      run: |
        yarn
        yarn test
    # - uses: amondnet/now-deployment@v1
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     zeit-token: ${{ secrets.ZEIT_TOKEN }}
    #     now-args: '--prod'
    - name: Prepare to deploy
      run: |
        yarn build
    - name: Deploy to Firebase
      run: |
        yarn firebase deploy --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Extract GCP SA
      run: |
        echo $PROD_GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      env:
        PROD_GCLOUD_SERVICE_KEY: ${{ secrets.PROD_GCLOUD_SERVICE_KEY }}
    - name: Use cloud-sdk
      uses: docker://google/cloud-sdk:217.0.0
    - name: Deploy
      run: |
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud app deploy --quiet --project My First Project