name: deploy-now
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Test
      run: |
        yarn
        yarn test
    - uses: amondnet/now-deployment@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        now-args: '--prod'
    - name: Prepare to deploy
      run: |
        yarn global add firebase-tools
        yarn build
    - name: Deploy to Firebase
      run: |
        yarn firebase deploy --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}